Bump to microsoft/vcpkg@c8696863d3
Changes: https://github.com/microsoft/vcpkg/compare/94ce0dab56f4d8ba6bd631ba59ed682b02d45c46...c8696863d371ab7f46e213d8f5ca923c4aef2a00

A recent build attempt failed downloading various mingw dependencies:

    Error: Failed to download from mirror set:
    https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404

Bumping to the latest vcpkg release tag appears to fix this.