Fix ZipEntry.Extract() declaration.
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder-release/137/

Commit ffffd815 introduced some compilation errors:

	ZipEntry.cs(245,134): error CS1031: Type expected
	ZipEntry.cs(245,134): error CS1001: Identifier expected

Remove the offending `, ,` so that libZipSharp can compile.